class TryCatch2{
    public static void main(String args[]){
        int a = 25;
        int b = 0;
        int c;
        try{
            c=a/b;
            System.out.println("value of c is: "+c);
        }
        catch(Exception e){
            System.out.println("exception caught"+e);
        }
    }
}
